"""Project root resolution from ``settings/paths.toml``, and the bash view of it.

Resolution order is ``settings/paths.toml`` -> environment variable -> hard failure.
There is deliberately NO guessed default. ``$SNIC_NOBACKUP`` has zero occurrences
across 2,073 prior-art source files (knowledge/prior_art.md §6): it is an assumption,
not a verified fact, so a fallback would resolve to a plausible-but-wrong path on the
cluster and the run would write somewhere nobody looks. An unset root is an error.

This mirrors the precedence chain of ``Pipeline/Riboseq/bin/site_env.sh`` (explicit
site key first, then this run's settings, then nothing) with its last tier — the
hard-coded ``/proj/nobackup/...`` table — removed on purpose.
"""

from __future__ import annotations

import os
import re
import shlex
import tomllib
from datetime import UTC, datetime
from pathlib import Path

SETTINGS_RELPATH = Path("settings") / "paths.toml"
ROOTS_TABLE = "roots"

_ENV_TEMPLATE = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?")
_SHELL_NAME = re.compile(r"[^A-Za-z0-9_]")


class PathsError(RuntimeError):
    """Raised when a root cannot be resolved, naming the fix."""


def load_paths(root: Path | None = None) -> dict:
    """Read ``settings/paths.toml`` and return its root entries.

    Args:
        root: Project directory holding ``settings/paths.toml``. Defaults to the
            nearest ancestor of the working directory that contains one.

    Returns:
        Mapping of root name to an entry dict with optional ``path`` and ``env`` keys.
        A bare string value in the toml is normalised to ``{'path': value}``.

    Raises:
        PathsError: If no ``settings/paths.toml`` is found, or it is malformed.
    """
    toml_file = _find_settings(root)
    try:
        data = tomllib.loads(toml_file.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise PathsError(f"{toml_file} is not valid TOML: {exc}") from exc

    table = data.get(ROOTS_TABLE, data)
    if not isinstance(table, dict):
        raise PathsError(f"{toml_file}: [{ROOTS_TABLE}] must be a table of root definitions.")
    return {name: _normalise_entry(name, value, toml_file) for name, value in table.items()}


def resolve_root(name: str, *, root: Path | None = None) -> Path:
    """Resolve one named root to an absolute path, or fail loudly.

    Args:
        name: Root name, as keyed under ``[roots]`` in ``settings/paths.toml``.
        root: Project directory holding the settings file. Defaults to a search
            upwards from the working directory.

    Returns:
        The resolved absolute path. Existence is NOT checked — an output root is
        routinely created by the job that resolves it.

    Raises:
        PathsError: If the name is absent from the toml and its environment
            variable is unset, or if a value interpolates an unset variable.
    """
    entries = load_paths(root)
    entry = entries.get(name)
    if entry is None:
        var = env_var_for(name)
        value = os.environ.get(var)
        if value:
            return Path(value).expanduser()
        raise PathsError(
            f"Root '{name}' is not defined. Add `{ROOTS_TABLE}.{name}` to "
            f"{SETTINGS_RELPATH}, or export {var}. Defined roots: "
            f"{', '.join(sorted(entries)) or '(none)'}."
        )
    return _resolve_entry(name, entry)


def env_var_for(name: str) -> str:
    """Environment variable name for a root, used both as fallback and in site.env.

    Args:
        name: Root name from ``settings/paths.toml``.

    Returns:
        The uppercased shell-safe variable name, e.g. ``data`` -> ``LABCORE_DATA_ROOT``.
    """
    return f"LABCORE_{_SHELL_NAME.sub('_', name).upper()}_ROOT"


def write_site_env(paths: dict, dest: Path) -> Path:
    """Generate a sourceable bash ``site.env`` from resolved roots, one-way.

    sbatch cannot source TOML, and two hand-maintained resolvers is exactly the drift
    this module exists to stop — so the generated file is derived, never edited. Any
    hand edit is lost on the next generation, which the header says out loud.

    Args:
        paths: Mapping of root name to a path string, a Path, or a ``load_paths``
            entry dict; entries are resolved the same way ``resolve_root`` resolves them.
        dest: File to write. Parent directories are created.

    Returns:
        The written file path.

    Raises:
        PathsError: If any entry cannot be resolved.
    """
    lines = [
        "# GENERATED by labcore.paths.write_site_env from settings/paths.toml.",
        "# DO NOT HAND-EDIT: regeneration overwrites this file without warning.",
        f"# Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}.",
        "",
    ]
    for name in sorted(paths):
        resolved = _resolve_entry(name, paths[name])
        lines.append(f"export {env_var_for(name)}={shlex.quote(str(resolved))}")
    lines.append("")

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest


def _find_settings(root: Path | None) -> Path:
    """Locate settings/paths.toml under root, or in the nearest ancestor of the cwd."""
    if root is not None:
        candidate = Path(root) / SETTINGS_RELPATH
        if candidate.is_file():
            return candidate
        raise PathsError(f"No {SETTINGS_RELPATH} under {root}.")

    start = Path.cwd().resolve()
    for directory in (start, *start.parents):
        candidate = directory / SETTINGS_RELPATH
        if candidate.is_file():
            return candidate
    raise PathsError(
        f"No {SETTINGS_RELPATH} found in {start} or any parent. Pass root=, or create it."
    )


def _normalise_entry(name: str, value: object, toml_file: Path) -> dict:
    """Coerce a toml root value into a {'path': ..., 'env': ...} entry."""
    if isinstance(value, str):
        return {"path": value, "env": None}
    if isinstance(value, dict):
        return {"path": value.get("path"), "env": value.get("env")}
    raise PathsError(
        f"{toml_file}: {ROOTS_TABLE}.{name} must be a path string or a table with "
        "'path' and/or 'env' keys."
    )


def _resolve_entry(name: str, entry: object) -> Path:
    """Resolve one entry: literal path, then its named environment variable, then fail."""
    if isinstance(entry, (str, os.PathLike)):
        entry = {"path": str(entry), "env": None}
    if not isinstance(entry, dict):
        raise PathsError(f"Root '{name}': expected a path or an entry dict, got {type(entry)}.")

    literal = entry.get("path")
    if literal:
        return Path(_expand(name, str(literal))).expanduser()

    var = entry.get("env") or env_var_for(name)
    value = os.environ.get(var)
    if value:
        return Path(value).expanduser()
    raise PathsError(
        f"Root '{name}' is unset: {SETTINGS_RELPATH} gives no path for it and "
        f"${var} is empty. Export {var}, or set {ROOTS_TABLE}.{name}.path in "
        f"{SETTINGS_RELPATH}. No default is guessed on purpose."
    )


def _expand(name: str, value: str) -> str:
    """Interpolate $VAR references in a toml value, failing on any that is unset."""
    missing = [var for var in _ENV_TEMPLATE.findall(value) if not os.environ.get(var)]
    if missing:
        raise PathsError(
            f"Root '{name}' references unset environment variable(s): "
            f"{', '.join('$' + var for var in missing)}. Export them, or replace the "
            f"reference with a literal in {ROOTS_TABLE}.{name}.path of {SETTINGS_RELPATH}."
        )
    return os.path.expandvars(value)
