"""Function-level index: one compact table per module, for `knowledge/api_index.md`.

Signatures and docstring summary lines only. Bodies are never read and project
code is never imported — Python goes through `ast`, everything else through
line-oriented scanning, so generating the index cannot execute a script.

Deviation from build plan §5.3, on the evidence in `knowledge/prior_art.md` §3:
bash functions are found by their `name()` definition and described by the
comment block directly above them, not by an invented `# fn:` marker. A grep for
that marker across ~/Scripts returned zero hits, so requiring it would make every
existing bash script invisible until hand-annotated.
"""

from __future__ import annotations

import ast
import importlib.util
import re
from dataclasses import dataclass
from pathlib import Path

from labcore.labdocs.walk import project_scripts

SCRIPT_SUFFIXES = (".py", ".R", ".r", ".rs", ".sh", ".bash")

_R_DEF = re.compile(r"^\s*([A-Za-z._][\w.]*)\s*(?:<-|=)\s*function\s*\((.*)$")
_RUST_FN = re.compile(r"^\s*pub(?:\s*\([^)]*\))?\s+(?:async\s+)?(?:unsafe\s+)?fn\s+(\w+)\s*(\(.*)$")
_BASH_FN = re.compile(r"^([a-z_][a-z0-9_]*)\(\)")


@dataclass(frozen=True)
class ApiEntry:
    """One documented function: what to call it, how to call it, what it does."""

    name: str
    signature: str
    summary: str


def build_api_index(root: Path) -> str:
    """Render the function-level index for a project as markdown.

    Covers ``scripts/**`` under ``root`` plus the installed ``labcore`` package,
    so an agent sees project-local and shared helpers in one file.

    Args:
        root: Project root containing a ``scripts/`` directory.

    Returns:
        Markdown document: one ``###`` heading and table per module that has at
        least one public function.
    """
    sections = [
        (path.relative_to(root).as_posix(), extract_functions(path))
        for path in _script_files(root)
    ]
    sections += [(f"labcore/{p.name}", extract_functions(p)) for p in _labcore_modules()]

    lines = ["# API index", "", "Generated by `labdocs api`. Do not hand-edit.", ""]
    for title, entries in sections:
        if entries:
            lines += _table(title, entries)
    return "\n".join(lines).rstrip() + "\n"


def write_api_index(root: Path) -> Path:
    """Write the index to ``knowledge/api_index.md``.

    Args:
        root: Project root.

    Returns:
        The path written.
    """
    out = root / "knowledge" / "api_index.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_api_index(root), encoding="utf-8")
    return out


def extract_functions(path: Path) -> list[ApiEntry]:
    """Extract public functions from one source file.

    Args:
        path: Source file; its extension selects the parser.

    Returns:
        Entries in source order, empty when the language is unsupported or the
        file does not parse.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    suffix = path.suffix.lower()
    if suffix == ".py":
        return _from_python(text)
    if suffix == ".r":
        return _from_r(text)
    if suffix == ".rs":
        return _from_rust(text)
    if suffix in (".sh", ".bash"):
        return _from_bash(text)
    return []


def _script_files(root: Path) -> list[Path]:
    """Every supported source file the project owns, in stable path order.

    Shares the linter's definition so the API index covers the same files the
    report and the linter do, including a flat repo's root-level scripts.
    """
    found = [p for p in project_scripts(root) if p.suffix in SCRIPT_SUFFIXES]
    return sorted(found, key=lambda p: p.as_posix())


def _labcore_modules() -> list[Path]:
    """Top-level labcore modules, located without importing the package."""
    spec = importlib.util.find_spec("labcore")
    if spec is None or spec.origin is None:
        return []
    root = Path(spec.origin).parent
    return sorted(p for p in root.glob("*.py") if not p.name.startswith("_"))


def _table(title: str, entries: list[ApiEntry]) -> list[str]:
    rows = [f"| `{e.name}` | `{e.signature}` | {_escape(e.summary)} |" for e in entries]
    return [f"### {title}", "| Function | Signature | Summary |", "|---|---|---|", *rows, ""]


def _escape(text: str) -> str:
    """Keep a summary from breaking out of its table cell."""
    return text.replace("|", "\\|").strip()


def _from_python(text: str) -> list[ApiEntry]:
    """Top-level public functions via ast — the module is parsed, never imported."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    entries = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        if node.name.startswith("_"):
            continue
        summary = (ast.get_docstring(node) or "").strip().splitlines()
        entries.append(ApiEntry(node.name, _py_signature(node), summary[0] if summary else ""))
    return entries


def _py_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Reconstruct a PEP 8 signature from the argument node."""
    args = node.args
    positional = args.posonlyargs + args.args
    padding: list[ast.expr | None] = [None] * (len(positional) - len(args.defaults))
    rendered = [
        _py_arg(a, d) for a, d in zip(positional, padding + list(args.defaults), strict=True)
    ]
    if args.posonlyargs:
        rendered.insert(len(args.posonlyargs), "/")
    if args.vararg:
        rendered.append("*" + _py_arg(args.vararg, None))
    elif args.kwonlyargs:
        rendered.append("*")
    rendered += [_py_arg(a, d) for a, d in zip(args.kwonlyargs, args.kw_defaults, strict=True)]
    if args.kwarg:
        rendered.append("**" + _py_arg(args.kwarg, None))
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"({', '.join(rendered)}){returns}"


def _py_arg(arg: ast.arg, default: ast.expr | None) -> str:
    """One parameter; annotated defaults get spaces around `=`, bare ones do not."""
    text = arg.arg
    if arg.annotation is not None:
        text += f": {ast.unparse(arg.annotation)}"
    if default is not None:
        joiner = " = " if arg.annotation is not None else "="
        text += joiner + ast.unparse(default)
    return text


def _from_r(text: str) -> list[ApiEntry]:
    """`name <- function(...)` assignments described by the roxygen2 block above."""
    lines = text.splitlines()
    entries = []
    for i, line in enumerate(lines):
        match = _R_DEF.match(line)
        if match is None:
            continue
        name, tail = match.group(1), match.group(2)
        entries.append(ApiEntry(name, _paren_span(tail, lines, i), _roxygen_summary(lines, i)))
    return entries


def _roxygen_summary(lines: list[str], index: int) -> str:
    """First untagged line of the contiguous `#'` block ending just above `index`."""
    block = []
    for line in reversed(lines[:index]):
        stripped = line.strip()
        if not stripped.startswith("#'"):
            break
        block.append(stripped[2:].strip())
    for candidate in reversed(block):
        if candidate and not candidate.startswith("@"):
            return candidate
    return ""


def _from_rust(text: str) -> list[ApiEntry]:
    """`pub fn` items described by the `///` doc comment above them."""
    lines = text.splitlines()
    entries = []
    for i, line in enumerate(lines):
        match = _RUST_FN.match(line)
        if match is None:
            continue
        entries.append(
            ApiEntry(match.group(1), _rust_signature(match.group(2)), _doc_summary(lines, i, "///"))
        )
    return entries


def _rust_signature(tail: str) -> str:
    """Params plus return type, stopping at the body brace or a trait declaration."""
    for terminator in ("{", ";"):
        head, sep, _ = tail.partition(terminator)
        if sep:
            tail = head
    return " ".join(tail.split())


def _doc_summary(lines: list[str], index: int, marker: str) -> str:
    """First non-empty line of the contiguous comment block ending just above `index`."""
    block = []
    for line in reversed(lines[:index]):
        stripped = line.strip()
        if not stripped.startswith(marker) or stripped.startswith("#!"):
            break
        body = stripped[len(marker) :].strip()
        if body:
            block.append(body)
        elif block:
            break
    return block[-1] if block else ""


def _from_bash(text: str) -> list[ApiEntry]:
    """`name()` definitions described by the `#` comment block directly above."""
    lines = text.splitlines()
    entries = []
    in_meta = False
    for i, line in enumerate(lines):
        # The codebase-meta block is script-level documentation; it would
        # otherwise be misread as the description of the first function below it.
        if line.strip().startswith("# ///"):
            in_meta = not in_meta
            continue
        match = _BASH_FN.match(line)
        if match is None or in_meta:
            continue
        entries.append(ApiEntry(match.group(1), "()", _doc_summary(lines, i, "#")))
    return entries


def _paren_span(tail: str, lines: list[str], index: int) -> str:
    """Signature text from an opening paren to its match, across wrapped lines."""
    collected = tail
    depth = 1 + tail.count("(") - tail.count(")")
    cursor = index
    while depth > 0 and cursor + 1 < len(lines):
        cursor += 1
        nxt = lines[cursor].strip()
        collected += " " + nxt
        depth += nxt.count("(") - nxt.count(")")
    body = collected[: collected.rfind(")")] if ")" in collected else collected
    return f"({' '.join(body.split())})"
