"""Render a project's `codebase-meta` blocks into the three generated artifacts.

One walk of the tree feeds one data structure, and HTML, JSON and Markdown are
three views of it — the technique lifted from `General_tools/paper_monitor.py`,
which renders the same digest as cards and as Markdown from one list of dicts
(prior_art.md §3). Doing it any other way is how the report and the map start
disagreeing about what the project does.

`explain_codebase.html` is one self-contained file: the stylesheet and the theme
toggle are inlined, and nothing is fetched at view time. prior_art.md §3 records
the Google Fonts `<link>` in `build_claude_inventory_report.py` as a live defect
— it breaks offline viewing and any strict CSP — so there is no external URL here
of any kind.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from html import escape
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path, PurePosixPath

import yaml

from labcore.labdocs import inventory
from labcore.labdocs.graph import dag_html, edges, language_of, mermaid_dag
from labcore.meta import COMMENT_TOKENS, MetaBlock, MetaError, extract_block

ASSETS = Path(__file__).parent / "assets"
BANNER = "GENERATED BY labdocs — do not hand-edit. Regenerate with `labdocs render`."

HTML_NAME = "explain_codebase.html"
MANIFEST_NAME = "codebase_manifest.json"
MAP_NAME = Path("knowledge") / "codebase_map.md"

# Directories walked for metadata blocks, and the roots whose files are shown by
# basename because their directory is already implied by the step's order.
SCRIPT_DIRS = ("scripts", "bin")
OUTPUT_ROOTS = ("outputs/", "deliverables/", "results/")

# Column order is fixed by the reference report and is part of the contract.
RUN_COLUMNS = (
    "#", "Script", "Path", "Inputs", "Outputs", "Key options", "Output meaning", "Goes to",
)

# The rendered timestamp is blanked before any staleness comparison, or every
# check would fail on the clock rather than on the content.
STAMP_RE = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z")


@dataclass
class Project:
    """Everything the renderers need, gathered by one walk of the tree."""

    root: Path
    name: str
    flavour: str
    steps: list[MetaBlock] = field(default_factory=list)
    helpers: list[MetaBlock] = field(default_factory=list)
    components: list[dict] = field(default_factory=list)
    nextflow_dag: str | None = None
    errors: list[tuple[Path, str]] = field(default_factory=list)

    def rel(self, path: Path) -> str:
        """Project-relative POSIX path, for display and for the manifest."""
        return path.relative_to(self.root).as_posix()


def labcore_version() -> str:
    """Report the installed labcore version for the reproducibility footer.

    Returns:
        The version string, or "unknown" when labcore is not installed as a package.
    """
    try:
        return version("labcore")
    except PackageNotFoundError:
        return "unknown"


def _utc_stamp() -> str:
    """Current UTC time in the one format STAMP_RE knows how to blank."""
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _walk_scripts(root: Path) -> tuple[list[MetaBlock], list[tuple[Path, str]]]:
    """Collect every parseable metadata block under the script directories."""
    blocks: list[MetaBlock] = []
    errors: list[tuple[Path, str]] = []
    for base in SCRIPT_DIRS:
        directory = root / base
        if not directory.is_dir():
            continue
        for path in sorted(directory.rglob("*")):
            if not path.is_file() or path.suffix not in COMMENT_TOKENS:
                continue
            try:
                block = extract_block(path)
            except MetaError as exc:
                errors.append((path, str(exc)))
                continue
            if block is not None:
                blocks.append(block)
    return blocks, errors


def load_project(root: Path) -> Project:
    """Walk a project and gather everything the renderers need.

    Args:
        root: Project root — the directory holding `scripts/` or `main.nf`.

    Returns:
        A Project with steps in run order, exempt helpers, and any parse errors.
        Pipeline projects additionally carry the component inventory and
        Nextflow's own `-with-dag` mermaid output when it sits at the root.
    """
    root = Path(root)
    settings = {}
    template = root / ".labtemplate.yml"
    if template.is_file():
        settings = yaml.safe_load(template.read_text(encoding="utf-8")) or {}

    detected = "pipeline" if (root / "main.nf").is_file() else "analysis"
    flavour = settings.get("flavour") or detected
    blocks, errors = _walk_scripts(root)
    project = Project(
        root=root,
        name=root.name,
        flavour=flavour,
        steps=sorted((b for b in blocks if not b.is_exempt), key=lambda b: (b.order or 0, b.name)),
        helpers=sorted((b for b in blocks if b.is_exempt), key=lambda b: b.name),
        errors=errors,
    )
    if flavour == "pipeline":
        project.components = inventory.components(root)
        dags = sorted(root.glob("*.mmd"))
        project.nextflow_dag = dags[0].read_text(encoding="utf-8") if dags else None
    return project


def build_manifest(project: Project) -> dict:
    """Assemble the machine-readable view of the project.

    Args:
        project: Loaded project.

    Returns:
        The dict written to `codebase_manifest.json`.
    """
    return {
        "_generated": BANNER,
        "generated_utc": _utc_stamp(),
        "labcore_version": labcore_version(),
        "project": project.name,
        "flavour": project.flavour,
        "steps": [
            {
                "order": step.order,
                "name": step.name,
                "path": project.rel(step.path),
                "language": language_of(step.path),
                "summary": step.data.get("summary", ""),
                "inputs": step.inputs,
                "outputs": step.outputs,
                "options": step.data.get("options") or [],
                "next": step.next_steps,
                "final": step.is_final or not step.next_steps,
                "container": step.data.get("container", ""),
            }
            for step in project.steps
        ],
        "helpers": [
            {"name": h.name, "path": project.rel(h.path), "exempt": h.data.get("exempt", "")}
            for h in project.helpers
        ],
        "components": project.components,
        "edges": [list(pair) for pair in edges(project)],
        "errors": [[project.rel(path), message] for path, message in project.errors],
    }


def _display_path(raw: str) -> str:
    """Show step outputs by filename; anything outside the output roots in full."""
    return PurePosixPath(raw).name if raw.startswith(OUTPUT_ROOTS) else raw


def _inputs_cell(items: list[dict]) -> str:
    """Input paths, with an `external` pill on inputs originating outside the DAG."""
    cells = []
    for item in items:
        pill = ' <span class="pill p2">external</span>' if item.get("external") else ""
        cells.append(f"<code>{escape(_display_path(item['path']))}</code>{pill}")
    return "<br>".join(cells) or "—"


def _outputs_cell(items: list[dict]) -> str:
    """Output paths, with streams shown as their destination rather than a filename."""
    cells = []
    for item in items:
        if item.get("pipe"):
            cells.append(
                f"<code>{escape(item['pipe'])}</code> → <code>{escape(item.get('to', ''))}</code>"
            )
        else:
            cells.append(f"<code>{escape(_display_path(item['path']))}</code>")
    return "<br>".join(cells) or "—"


def _options_cell(options: list[dict]) -> str:
    """Flags with their prose and declared defaults."""
    cells = []
    for opt in options:
        text = f"<code>{escape(opt['flag'])}</code> {escape(opt['desc'].rstrip('.'))}"
        if "default" in opt:
            text += f" (default {escape(str(opt['default']))})"
        cells.append(text)
    return "<br>".join(cells) or "—"


def _next_cell(step: MetaBlock) -> str:
    """Downstream steps, or the terminal pill."""
    if step.is_final or not step.next_steps:
        return '<span class="pill p3">final</span>'
    return "<br>".join(f"<code>{escape(name)}</code>" for name in step.next_steps)


def _table(columns: tuple[str, ...], rows: list[str]) -> str:
    """One table with a header row and pre-rendered `<tr>` bodies."""
    head = "".join(f"<th>{escape(col)}</th>" for col in columns)
    body = "\n".join(rows)
    return (
        f"<table>\n  <thead>\n    <tr>{head}</tr>\n  </thead>\n"
        f"  <tbody>\n{body}\n  </tbody>\n</table>"
    )


def _run_row(project: Project, step: MetaBlock) -> str:
    """One run-order row, columns in the order the reference fixes them."""
    meaning = "<br>".join(escape(out.get("desc", "")) for out in step.outputs) or "—"
    # The summary rides as a tooltip rather than a ninth column: the column set is
    # fixed by the reference report, but a summary the HTML never carries is a
    # summary `render --check` cannot notice going stale.
    summary = escape(step.data.get("summary", ""), quote=True)
    return (
        "    <tr>\n"
        f'      <td>{step.order or 0:02d}</td>'
        f'<td><strong title="{summary}">{escape(step.name)}</strong></td>'
        f"<td><code>{escape(project.rel(step.path))}</code></td>\n"
        f"      <td>{_inputs_cell(step.inputs)}</td><td>{_outputs_cell(step.outputs)}</td>\n"
        f"      <td>{_options_cell(step.data.get('options') or [])}</td>\n"
        f"      <td>{meaning}</td><td>{_next_cell(step)}</td>\n"
        "    </tr>"
    )


def _helpers_section(project: Project) -> str:
    """Exempt helper modules, listed so an opt-out stays visible rather than silent."""
    if not project.helpers:
        return ""
    rows = [
        f"    <tr><td><strong>{escape(h.name)}</strong></td>"
        f"<td><code>{escape(project.rel(h.path))}</code></td>"
        f"<td>{escape(h.data.get('exempt', ''))}</td></tr>"
        for h in project.helpers
    ]
    return "<h3>Helpers (exempt from the run order)</h3>\n" + _table(
        ("Module", "Path", "Why exempt"), rows
    )


def _errors_section(project: Project) -> str:
    """Files whose block refused to parse — loud in the report, not swallowed."""
    if not project.errors:
        return ""
    items = "".join(
        f"<li><code>{escape(project.rel(p))}</code> — {escape(m)}</li>" for p, m in project.errors
    )
    return f'<div class="callout"><strong>Unparseable metadata.</strong><ul>{items}</ul></div>'


def _analysis_body(project: Project) -> str:
    """Dataflow DAG plus the run-order table."""
    rows = [_run_row(project, step) for step in project.steps]
    return "\n".join(
        [
            "<h3>Dataflow</h3>",
            dag_html(project),
            '<details class="src"><summary>Mermaid source for the same graph</summary>',
            f"<pre><code>{escape(mermaid_dag(project))}</code></pre></details>",
            "<h3>Run order</h3>",
            _table(RUN_COLUMNS, rows),
        ]
    )


def _pipeline_body(project: Project) -> str:
    """Component inventory, and Nextflow's own DAG when the run produced one.

    No run order and no derived DAG: nf-core `meta.yml` carries neither `order:`
    nor `next:`, and inventing them would be a lie about what runs when
    (build plan §5.3).
    """
    parts = ["<h3>Component inventory</h3>"]
    if project.components:
        rows = [inventory.html_row(c) for c in project.components]
        parts.append(_table(inventory.INVENTORY_COLUMNS, rows))
    else:
        parts.append("<p>No <code>meta.yml</code> sidecars found under <code>modules/</code>.</p>")
    if project.nextflow_dag:
        parts += [
            "<h3>Dataflow (Nextflow <code>-with-dag</code>)</h3>",
            f"<pre><code>{escape(project.nextflow_dag)}</code></pre>",
        ]
    return "\n".join(parts)


def _page(project: Project) -> str:
    """Build the whole self-contained report page."""
    css = (ASSETS / "report.css").read_text(encoding="utf-8")
    js = (ASSETS / "report.js").read_text(encoding="utf-8")
    body = _analysis_body(project) if project.flavour == "analysis" else _pipeline_body(project)
    lede = (
        "Generated from the fenced <code>codebase-meta</code> blocks in each script"
        if project.flavour == "analysis"
        else "Generated from the nf-core <code>meta.yml</code> sidecars"
    )
    footer = (
        f"Generated by <strong>labdocs</strong> (labcore {escape(labcore_version())}) at "
        f'<span class="mono-sm">{_utc_stamp()}</span> — {escape(BANNER)} '
        "Palette: Okabe-Ito colourblind-safe."
    )
    return f"""<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(project.name)} — explain_codebase</title>
<!-- {escape(BANNER)} -->
<style>
{css}</style>
</head>
<body>
<div class="wrap">

<header>
  <div>
    <h1>{escape(project.name)}</h1>
    <p class="sub">Generated codebase report · <code>{escape(project.flavour)}</code> flavour ·
      {len(project.steps)} steps</p>
  </div>
  <button class="tg" id="tg">◐ Dark theme</button>
</header>

<p class="lede">{lede}. Never hand-written, and kept honest by the
<code>labdocs render --check</code> prek hook.</p>

{body}
{_helpers_section(project)}
{_errors_section(project)}

<footer>{footer}</footer>

</div>
<script>
{js}</script>
</body>
</html>
"""


def _md_cell(cells: list[str]) -> str:
    """Join multi-valued Markdown table cells, which cannot hold block markup."""
    return " · ".join(cells) if cells else "—"


def _md_text(text: str) -> str:
    """Neutralise prose that would otherwise break out of a Markdown table cell."""
    return text.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def _md_row(project: Project, step: MetaBlock) -> str:
    """The same run-order data as one Markdown table row."""
    inputs = [
        f"`{_display_path(i['path'])}`" + (" (external)" if i.get("external") else "")
        for i in step.inputs
    ]
    outputs = [
        f"`{o['pipe']}` → `{o.get('to', '')}`" if o.get("pipe") else f"`{_display_path(o['path'])}`"
        for o in step.outputs
    ]
    options = [
        f"`{o['flag']}` {_md_text(o['desc'].rstrip('.'))}"
        + (f" (default {o['default']})" if "default" in o else "")
        for o in step.data.get("options") or []
    ]
    goes_to = (
        "**final**"
        if step.is_final or not step.next_steps
        else _md_cell([f"`{n}`" for n in step.next_steps])
    )
    meaning = _md_cell([_md_text(o.get("desc", "")) for o in step.outputs])
    return (
        f"| {step.order or 0:02d} | **{step.name}** | `{project.rel(step.path)}` | "
        f"{_md_cell(inputs)} | {_md_cell(outputs)} | {_md_cell(options)} | {meaning} | {goes_to} |"
    )


def _md_header(columns: tuple[str, ...]) -> list[str]:
    """Markdown table header plus its separator row."""
    return ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]


def _map_text(project: Project) -> str:
    """Build knowledge/codebase_map.md from the same data as the HTML."""
    helpers = len(project.helpers)
    counts = f"{len(project.steps)} steps · {helpers} exempt helper{'' if helpers == 1 else 's'}"
    lines = [
        f"<!-- {BANNER} -->",
        "",
        f"# Codebase map — {project.name}",
        "",
        f"_{project.flavour} flavour · {counts}_",
        "",
    ]
    if project.flavour == "analysis":
        lines += [
            *_md_header(RUN_COLUMNS),
            *[_md_row(project, step) for step in project.steps],
            "",
            "## Dataflow",
            "",
            "```mermaid",
            mermaid_dag(project),
            "```",
            "",
        ]
    else:
        lines += [
            *_md_header(inventory.INVENTORY_COLUMNS),
            *[inventory.md_row(c) for c in project.components],
            "",
        ]
    if project.helpers:
        lines += ["## Helpers (exempt)", ""]
        lines += [
            f"- `{project.rel(h.path)}` — {h.data.get('exempt', '')}" for h in project.helpers
        ]
        lines += [""]
    lines += [
        "---",
        "",
        f"Generated by labdocs (labcore {labcore_version()}) at {_utc_stamp()}. {BANNER}",
        "",
    ]
    return "\n".join(lines)


def render_html(project: Project, out: Path) -> Path:
    """Write the self-contained `explain_codebase.html`.

    Args:
        project: Loaded project.
        out: Destination file.

    Returns:
        The path written.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_page(project), encoding="utf-8")
    return out


def render_map(project: Project, out: Path) -> Path:
    """Write `knowledge/codebase_map.md` — the run order as Markdown.

    Args:
        project: Loaded project.
        out: Destination file.

    Returns:
        The path written.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_map_text(project), encoding="utf-8")
    return out


def _artifacts(project: Project) -> dict[Path, str]:
    """Every generated file's final text, keyed by destination."""
    manifest = json.dumps(build_manifest(project), indent=2, ensure_ascii=False, default=str)
    return {
        project.root / HTML_NAME: _page(project),
        project.root / MANIFEST_NAME: manifest + "\n",
        project.root / MAP_NAME: _map_text(project),
    }


def _is_stale(path: Path, fresh: str) -> bool:
    """Compare on-disk text against a fresh render, ignoring the timestamp."""
    if not path.is_file():
        return True
    blank = "0000-00-00T00:00:00Z"
    return STAMP_RE.sub(blank, path.read_text(encoding="utf-8")) != STAMP_RE.sub(blank, fresh)


def render_all(root: Path, *, check: bool = False) -> list[Path]:
    """Render every generated artifact, or report which ones are out of date.

    Args:
        root: Project root.
        check: When True, write nothing and instead compare each artifact against
            a fresh render. This is the staleness guard the prek hook runs; a
            non-empty return means the commit must fail.

    Returns:
        Paths written, or — under `check` — the paths that are stale or missing.
        Empty under `check` means everything on disk matches the metadata.
    """
    project = load_project(root)
    targets = _artifacts(project)
    if check:
        return [path for path, fresh in targets.items() if _is_stale(path, fresh)]
    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return list(targets)


def check_stale(root: Path) -> list[Path]:
    """Report generated files that no longer match the metadata.

    The name `labdocs render --check` looks for; the behaviour lives in
    `render_all`.

    Args:
        root: Project root.

    Returns:
        Stale or missing artifact paths; empty when everything is current.
    """
    return render_all(root, check=True)
